(function(root){
  const verifiedOn='2026-10-03';
  const source=(sourceId,title,url,publisher,examCycle,locator='',access='open')=>({sourceId,title,url,publisher,examCycle,locator,sourceType:'official',access,verificationStatus:'verified',verifiedOn});
  const sources=[
    source('ftii-prospectus','FTII ET 2025–26 prospectus','https://ftii.ac.in/api/serve/2026/04/09/Admission_Prospectus_FTII-ET-2025-26_1775711367_d6832d9b.pdf','FTII','2025–26','Printed pp. 3, 55, 62–67, 75–83, 87–89, 95–97'),
    source('ftii-course','FTII Screen Acting programme','https://ftii.ac.in/screen-acting','FTII','Institutional course page'),
    source('ftii-scholarships','FTII scholarships','https://ftii.ac.in/scholarships','FTII','Institutional scheme list','Acting rows; state and NSP schemes'),
    source('ftii-admissions','FTII admission notices','https://ftii.ac.in/admission-process-6','FTII','2025–26','Later notices supersede prospectus schedules','portal'),
    source('nsd-notice','NSD admission notice 2026','https://nsd.gov.in/delhi/wp-content/uploads/2026/03/nsd_admission_2026.pdf','NSD','2026–2029','PDF pp. 4–6 (English)'),
    source('nsd-prospectus','NSD English prospectus 2026','https://drive.google.com/file/d/1FyU4kjJz5nHCEf4f__nGvz69y492Ce9i/view','NSD','2026–2029','Official link from NSD website; printed pp. 7–18; fees and scholarship p. 16'),
    source('nsd-course','NSD course and prospectus links','https://nsd.gov.in/delhi/index.php/course-in-dramatic-arts/','NSD','Institutional course page','Older year-based curriculum differs from 2026 notice; 2026 notice takes priority'),
    source('nsd-portal','NSD admission portal','https://admission.nsd.gov.in/','NSD','2026','Entry page confirms closed; last date 17 April 2026','portal'),
    source('nsd-uploads','NSD portal upload guidance','https://admission.nsd.gov.in/src/pages/UploadDocuments.tsx','NSD','2026','Public portal client instructions retrieved without login; upload limits are portal guidance, not eligibility waivers','reference')
  ];
  const fact=(section,label,ftii,nsd,ftiiSources=['ftii-prospectus'],nsdSources=['nsd-notice'],status='official')=>({section,label,ftii,nsd,ftiiSources,nsdSources,status});
  const facts=[
    fact('Course','Programme','MFA in Cinema with specialization in Screen Acting, Pune.','Three-year full-time residential Diploma in Dramatics, New Delhi.'),
    fact('Course','Duration and intake','2 years; 4 semesters; 80 credits; 16 seats.','3 years; 6 semesters of 20 weeks; 32 seats, with up to 3 for fully paying foreign nationals.',['ftii-course']),
    fact('Course','Eligibility','Bachelor’s degree or equivalent in any discipline. Final-year applicants may apply provisionally.','Graduation in any stream from a recognised university; at least 6 different theatre productions with documentary proof; working Hindi/English.'),
    fact('Course','Age','No upper age limit stated for Screen Acting in this prospectus. DOB must match Class 10 certificate.','18–30 on 1 July 2026; upper-age relaxation: SC/ST 5 years, OBC-NCL 3 years under the notice.'),
    fact('Curriculum','Foundation','Semester 1: filmmaking foundation plus improvisation, sensory work, imagination and emotional exploration.','First 3 semesters: integrated training. Acting, theatre techniques, theatre history, literature and aesthetics form the foundation.',['ftii-course'],['nsd-notice','nsd-prospectus']),
    fact('Curriculum','Specialization and projects','Semester 2: full-length theatre production. Semester 3: character, script analysis and camera performance. Semester 4: workshops/masterclasses and thesis film.','Next 3 semesters: Acting or Design & Direction. Design & Direction specialization is available to 5 students. Practical productions support training.',['ftii-course'],['nsd-notice','nsd-prospectus']),
    fact('Curriculum','Craft training','Voice/speech, movement, monologues, scenes, psychological gesture, yoga, Kalaripayattu, Chhau, Thangta, stunts/action and contemporary dance.','Acting, voice/speech, movement, music, improvisation, Indian and Western theatre, classical/folk traditions and stagecraft.',['ftii-course'],['nsd-prospectus']),
    fact('Fees','Application fee','Single programme: ₹1,500 General/OBC-NCL/GEN-EWS; ₹500 SC/ST/PwD/female. Two programmes: ₹2,500 / ₹800 respectively. Non-refundable; bank charges extra.','₹50 online application fee (2026 notice).'),
    fact('Fees','Tuition','Semester 1 ₹46,885; semesters 2–4 ₹46,884 each.','₹300 per month.',['ftii-prospectus'],['nsd-prospectus']),
    fact('Fees','Hostel and other charges','Semester 1 ₹62,689 including deposits; each remaining semester ₹19,408. Hostel rent component ₹15,241 per semester.','Hostel ₹1,000/month; electricity/water ₹150, adjustable to consumption; lunch/dinner mess ₹4,000/month, variable. Hostel residence compulsory.',['ftii-prospectus'],['nsd-prospectus']),
    fact('Fees','Joining payments and deposits','Security ₹25,393; hostel ₹6,348; mess ₹5,084; library ₹6,327 (included in semester-1 charges). Handbook ₹129 one time.','Admission ₹500; union membership ₹100/year; caution/library deposit ₹10,000 refundable after settlement; stationery ₹2,500; insurance listed ₹650/month. Keep ₹1,000 additional joining provision.',['ftii-prospectus'],['nsd-prospectus']),
    fact('Fees','Budget boundary','Semester 1 total ₹1,09,574; later semester ₹66,292 each. Four-semester sum ₹3,08,450, calculated at the published unchanged rates. Includes deposits; excludes application, ongoing mess, travel/personal expenses.','No official all-in three-year total stated. Tuition, hostel, mess, insurance and other dues are separate. Insurance is deducted from scholarship; confirm billing and deductions at joining.',['ftii-prospectus'],['nsd-prospectus'],'official + calculated budget'),
    fact('Funding','Monthly stipend / scholarship','No universal monthly stipend verified for Screen Acting in the reviewed sources. Competitive awards and eligible external schemes are listed separately.','₹9,500/month scholarship to selected admitted diploma students for academic/training expenses. Foreign seats are fully paid; embassy/ICCR funding has separate rules.',['ftii-scholarships','ftii-prospectus'],['nsd-notice','nsd-prospectus']),
    fact('Funding','Merit scholarships','Acting entrance: Bachchan Patra ₹50,000 (1st), FTII ₹25,000 (2nd), ₹22,500 (3rd). Semester 1: ₹25,000/₹22,500 top two. Semester 2: Shatrughan Sinha ₹75,000; Sonakshi Sinha ₹75,000 (female topper, male fallback); Kaifi Azmi ₹50,000 merit + income; FTII ₹25,000/₹22,500 excluding those awardees. Semester 3 top two ₹25,000/₹22,500. Semester 4 Sanjeev Kumar ₹51,000 topper. These are awards, not monthly payments.','The monthly scholarship is the main published support for this diploma; no separate universal stipend verified.',['ftii-scholarships'],['nsd-prospectus']),
    fact('Funding','Fee concession / external schemes','EWS freeship: 30% of tuition + hostel rent only; apply after admission, renew each semester with supporting evidence and satisfactory progress/attendance/discipline. State/NSP schemes depend on domicile/category/income and active scheme rules; verify applicability before budgeting.','Selected students must submit a prescribed undertaking that they receive no scholarship from another source.',['ftii-prospectus','ftii-scholarships'],['nsd-prospectus']),
    fact('Funding','State scholarships listed by FTII','Bihar: actual tuition fees for eligible state-domicile students. Telangana: ₹20,000/year for eligible state-domicile students. No West Bengal-specific scholarship is listed in the reviewed FTII table; this does not establish that no external Bengal scheme exists. Confirm current state rules and sanction.','The diploma’s own monthly scholarship has a non-receipt-of-other-scholarship undertaking.',['ftii-scholarships'],['nsd-prospectus']),
    fact('Funding','NSP schemes listed by FTII','FTII’s table lists Top Class ST (family income below ₹6 lakh/year), Top Class SC (below ₹8 lakh/year; 1 slot shown), and PM YASASVI OBC/EBC/DNT (table’s OBC income below ₹2.5 lakh/year; 5 slots shown). Each lists ₹86,000 in year 1 and ₹41,000 in later years for accessories/stationery/stipend, plus actual paid fees. These are annual packages, not monthly stipends. Scheme ministry rules, available slots and active NSP eligibility must be confirmed before applying.','No additional universal stipend verified. Foreign students can seek embassy/ICCR assistance under their separate rules.',['ftii-scholarships'],['nsd-prospectus']),
    fact('Funding','Conditions','Merit awards are competitive. Do not assume all awards can be combined or deducted from joining fees. Confirm the scheme’s current award letter.','Scholarship bond ₹3,42,000: repay money received if leaving before 3 years or discontinued for discipline. 85% semester attendance mandatory; 75–84% loses scholarship/facilities. Insurance and materials may be deducted.',['ftii-scholarships'],['nsd-prospectus']),
    fact('Timeline','Cycle covered','ET 2025–26, applications held in calendar 2026.','Diploma 2026–2029, applications held in calendar 2026.'),
    fact('Timeline','Form release','11 March 2026.','17 March 2026.'),
    fact('Timeline','Submission deadline','7 April 2026, 6 pm (India time), published registration deadline.','17 April 2026; notice gives no closing hour. Portal confirms this date and that applications are closed.'),
    fact('Timeline','Selection schedule','Original written-test schedule: 26 April 2026; admit cards 18–25 April. Audition June–July was tentative. A later re-examination notice exists; use the notices page and individual call letter for revised dates.','Preliminary auditions: 16 May–2 June 2026 by centre; Kolkata 19–20 May. Final workshop in Delhi 15–19 June; scheduled course start 15 July 2026.'),
    fact('Timeline','Pending documents','If OBC-NCL/EWS certificate pending: upload timely application acknowledgement; valid certificate due 7 May 2026, 4 pm. Final-year degree passing proof due 31 July 2026, 4 pm. These are past-cycle conditions.','Public portal provides a final-year graduation undertaking upload. The notice requires graduation; obtain explicit NSD confirmation of the final passing-proof deadline before relying on provisional eligibility.',['ftii-prospectus'],['nsd-notice','nsd-uploads']),
    fact('Timeline','Next application cycle','Next release/deadline not verified as announced on 3 October 2026. Do not reuse the 2026 dates for the next intake.','Next release/deadline not verified as announced on 3 October 2026. Do not reuse the 2026 dates for the next intake.',['ftii-admissions'],['nsd-course','nsd-portal'],'not announced / not verified')
  ];
  const doc=(id,title,appliesTo,stage,note,sourceIds,requirement='required')=>({id,title,appliesTo,stage,note,sourceIds,requirement});
  const documents=[
    doc('admission-photo','Recent passport-size colour photo','Both','Application','FTII: follow portal image specifications. NSD: JPG/PNG ≤500 KB; 200 DPI recommended.',['ftii-prospectus','nsd-uploads']),
    doc('admission-signature','Candidate signature','Both','Application','NSD: JPG/PNG ≤200 KB, black/blue ink on white paper. FTII: follow its portal specifications.',['ftii-prospectus','nsd-uploads']),
    doc('admission-id','Photo identity proof','Both','Application / examination','NSD upload: Aadhaar, passport or voter ID ≤500 KB. FTII examination: original photo ID (Aadhaar, voter card, driving licence, college/university ID or PAN).',['ftii-prospectus','nsd-uploads']),
    doc('admission-school','Class 10 / DOB and Class 12 records','Both','Application / verification','FTII DOB must match Class 10/SSC. Keep Class 12 qualification records. NSD portal provides separate Class 10/12 uploads ≤500 KB each; current client form makes these optional uploads. Preserve originals for verification.',['ftii-prospectus','nsd-uploads'],'stage-specific'),
    doc('graduation','Graduation degree / marksheets','Both','Application / verification','Recognised degree and academic proof. NSD graduation file ≤1 MB (PDF/JPG/PNG). Keep original degree/provisional certificate and marksheets for verification.',['ftii-prospectus','nsd-notice','nsd-uploads']),
    doc('admission-category','SC/ST, OBC-NCL, EWS and disability evidence','Both','Application / verification','Only if claiming the category. Use prescribed competent-authority certificates. FTII OBC-NCL: Central list/format; EWS income/assets certificate; valid current-cycle documents. NSD upload fields ≤500 KB each (PDF/JPG/PNG); permissive portal validation does not waive eligibility proof.',['ftii-prospectus','nsd-notice','nsd-uploads'],'conditional'),
    doc('admission-receipt','Submitted application and payment record','Both','After submission','Keep the final application, application number and fee receipt. FTII uses a payment reference and SBI Collect transaction record.',['ftii-prospectus','nsd-notice'],'keep record'),
    doc('admission-call','Printed admit card / audition call letter','Both','Examination / workshop','FTII requires printed admit card and original photo ID; digital admit cards are not accepted. NSD dates and workshop instructions arrive by email / portal.',['ftii-prospectus','nsd-notice'],'stage-specific'),
    doc('admission-medical','Medical fitness evidence','Both','After selection','FTII arranges/informs the medical-test process. NSD requires a recognised-authority medical certificate and campus/panel fitness examination before joining. Follow the selection letter rather than obtaining an arbitrary format.',['ftii-prospectus','nsd-prospectus','nsd-notice'],'stage-specific'),
    doc('admission-final-year','Final-year / pending graduation proof','Both','Conditional application / selection','FTII passing certificate/marksheet/provisional certificate with roll/register number due by 31 July 2026, 4 pm in this cycle. NSD public portal offers a graduation undertaking ≤1 MB; its acceptance and passing-proof deadline need confirmation.',['ftii-prospectus','nsd-notice','nsd-uploads'],'conditional'),
    doc('admission-recognition','Degree recognition / equivalence evidence','FTII','Application','Recognition valid for the university, course and study period (UGC/AIU); equivalence evidence for diploma claimed equal to a bachelor’s; DEB recognition for distance/open-university qualifications.',['ftii-prospectus'],'conditional to qualification'),
    doc('admission-translation','Certified Hindi/English translation','FTII','Document verification','For certificates in another language, upload original plus duly certified, notarised Hindi/English translation as one PDF.',['ftii-prospectus'],'conditional'),
    doc('admission-pending-category','Pending OBC-NCL / EWS acknowledgement','FTII','Conditional application','Acknowledgement date no later than application submission; valid certificate due 7 May 2026, 4 pm for ET 2025–26.',['ftii-prospectus'],'conditional'),
    doc('six-productions','Proof of 6 different theatre productions','NSD','Application / verification','Attach participation certificate, brochure, leaflet or newspaper clips for each distinct production. Use the production log below to assemble proof; a tick or log entry alone is not an uploaded application.',['nsd-notice']),
    doc('admission-nsd-undertaking','Scholarship undertaking and repayment bond','NSD','After selection','Prescribed non-receipt-of-other-scholarship undertaking and ₹3,42,000 scholarship bond. Obtain current NSD forms.',['nsd-prospectus']),
    doc('admission-nsd-passport','Passport ready before joining','NSD','After selection','2026 prospectus advises selected students to get their passport ready. Foreign applicants have a separate passport upload ≤1 MB and fully paid seats.',['nsd-prospectus','nsd-uploads'],'advised; required for foreign identification'),
    doc('admission-ftii-freeship','Income / supporting concession documents','FTII','After admission','If applying for EWS freeship, provide the relevant current supporting documents and renew each semester. For external scholarships follow each scheme’s evidence requirements.',['ftii-prospectus','ftii-scholarships'],'conditional'),
    doc('admission-ftii-withdrawal','Withdrawal / resignation certificate','FTII','Admission','If already enrolled elsewhere or employed, produce a withdrawal/resignation certificate from that institution or organisation. FTII prohibits concurrent academic/professional engagement.',['ftii-prospectus'],'conditional'),
    doc('admission-ftii-insurance','Mediclaim policy details','FTII','Admission / course','Mediclaim coverage is compulsory for the complete course at the student’s expense. If already covered for the academic session, submit the existing policy details. Confirm coverage and renewal instructions at joining.',['ftii-prospectus'],'required at admission'),
    doc('recommendation','Expert recommendation — check current instructions','NSD','Only if requested','The existing tracker included this from earlier guidance. The reviewed 2026 admission notice does not list it as an essential document. Retained as optional readiness, not a confirmed compulsory 2026 requirement.',['nsd-notice'],'not confirmed for 2026'),
    doc('language','Working Hindi / English','NSD','Eligibility','An eligibility check, not a separately prescribed language certificate in the 2026 notice.',['nsd-notice'],'eligibility check'),
    doc('cycle-check','Age / category eligibility','NSD','Before application','Check the date-of-birth cut-off and applicable relaxation against the notice for the intake you apply to.',['nsd-notice'],'eligibility check')
  ];
  const movedResourceIds=['r0','r1','r13','r14','r15','r16'];
  const data={verifiedOn,scope:'FTII Pune Screen Acting and NSD New Delhi Diploma only. Indian-applicant fees; foreign admissions have separate terms.',sources,facts,documents,movedResourceIds,gaps:[
    'Next-cycle release dates, deadlines and fee revisions have not been verified as announced. This is a dated reference, not a live admissions feed.',
    'FTII upload byte limits, final joining forms and photocopy counts must be checked in the active portal/call letter. Do not assume a fixed number of copies.',
    'NSD final-year passing-proof deadline and any additional joining documents need the active call letter. Portal upload fields and optional validation do not override the official notice.',
    'NSD’s older course webpage describes specialization from year two; the 2026 notice specifies the first three semesters integrated and the next three specialized. The sheet follows the 2026 notice.'
  ]};
  root.ACTING_ADMISSIONS=data;
  if(typeof module!=='undefined')module.exports=data;
})(typeof window==='undefined'?globalThis:window);
