// Public bibliography only. Personal viewing/reflection records live in app state.
window.ACTING_CINEMA = {
  version: "2026-09-27",
  sourceType: "supplementary",
  accessNote: "India: lawful full-film availability not verified. Links are institutional/distributor references, not promises of streaming access. Check regional rights, subtitles and content advice before each assignment.",
  scopeNote: "A curated starting map, not a complete canon or an official FTII/NSD watchlist. Study regions are cultural contexts, not claims of exclusive nationality. Films and filmmakers do not represent an entire country. Runtime refers to the linked edition and can vary.",
  mapping: {
    ftii: "Preparation mapping: world cinema awareness, actor/director choices, framing, eyeline, continuity and defensible interview examples (ftii-cinema / app ftii-screen; ftii-interview).",
    nsd: "Preparation mapping: character objectives, conflict, voice/body interpretation and critical expression (shared-theory, shared-analysis, nsd-written). Watching an adaptation never replaces a prescribed play.",
    bengal: "Comparison layer: use Ray, Ghatak and Mrinal Sen as starting points, not fixed style labels. Compare observable choices, social context and stage-to-camera scale (bengal-screen)."
  },
  starterIds: ["bicycle-thieves", "400-blows", "rashomon", "chungking", "separation", "cleo", "do-right", "parasite", "black-girl", "tokyo-story", "close-up", "all-mother"],
  modules: [
    {id:"world-foundation",title:"International cinema: foundation",topics:["Subtitles and performance observation", "Objective, obstacle and listening across languages", "Framing, editing and actor contribution", "Separate observation from interpretation"]},
    {id:"world-movements",title:"International cinema: movements and context",topics:["Italian neorealism", "French New Wave and Left Bank", "Japanese postwar family and testimony", "Hong Kong and New Taiwan Cinema", "Iranian realism and documentary-fiction", "New Korean Cinema and class", "African postcolonial and transnational cinema", "Latin American class, memory and urban life", "Feminist cinema and domestic labour", "European modernism and Romanian New Wave", "Cult reception, soundtracks and formal experimentation"]},
    {id:"world-evidence",title:"International cinema: optional actor exploration",optional:true,topics:["Twelve foundation film dossiers", "One stage/close-up original-scene comparison", "One Bengal/international comparison", "One supported 200-word critical response", "One recorded interview answer using a film example"]}
  ],
  // Fields: id, title, year, directors, study region, production countries (catalogue),
  // language(s), edition minutes, movement/context, path, cultural note, actor focus,
  // Bengal comparison prompt, observation question, source, publisher, content heads-up.
  films: [
    ["bicycle-thieves","Bicycle Thieves",1948,["Vittorio De Sica"],"Italy","Italy","Italian",89,"Italian neorealism","Foundation","Postwar work and poverty anchor a landmark of neorealism; ordinary lives become central dramatic material.","Objective / obstacle","Compare everyday social pressure with Ray without assuming identical methods.","How does a practical need change the character's tactics toward another person?","https://www.criterion.com/films/210-bicycle-thieves","Criterion","Poverty and emotional distress."],
    ["400-blows","The 400 Blows",1959,["François Truffaut"],"France","France","French",99,"French New Wave","Foundation","A personal childhood story helped establish the French New Wave's author-led, youthful perspective.","Behaviour / relationship","Compare a child's observable behaviour with a Ray character study.","Where does behaviour contradict what an adult thinks the child wants?","https://www.criterion.com/films/151","Criterion","Child neglect and distress."],
    ["rashomon","Rashomon",1950,["Akira Kurosawa"],"Japan","Japan","Japanese",88,"Postwar Japanese cinema","Foundation","Conflicting testimony made truth and self-presentation central to a major international breakthrough for Japanese cinema.","Objective / obstacle","Compare heightened gesture with a Ghatak performance, accounting for framing and context.","How do posture and status change when a person narrates their own version?","https://www.criterion.com/films/307-rashomon","Criterion","Sexual assault and murder themes; check detailed advice first."],
    ["chungking","Chungking Express",1994,["Wong Kar Wai"],"Hong Kong","Hong Kong","Cantonese (catalogue primary language)",102,"1990s Hong Kong urban cinema","Foundation","Urban loneliness, pop music and fragmented romance make this a defining work of 1990s cinema.","Listening / subtext","Compare romantic longing with Charulata; distinguish actor choices from music and editing.","What does an apparently casual routine reveal without explanatory dialogue?","https://www.criterion.com/films/226","Criterion","Crime and relationship distress."],
    ["separation","A Separation",2011,["Asghar Farhadi"],"Iran","Iran","Persian / Farsi",123,"Contemporary Iranian social drama","Foundation","Family responsibility and conflicting obligations shape a moral drama that refuses easy judgements.","Objective / obstacle","Compare social constraint with a Mrinal Sen character; avoid turning either into a national stereotype.","Can you defend two opposing characters' objectives using different pieces of evidence?","https://www.sonyclassics.com/aseparation/aseparation_presskit.pdf","Sony Pictures Classics","Family conflict and distress."],
    ["cleo","Cléo from 5 to 7",1962,["Agnès Varda"],"France","France","French",89,"Left Bank / French New Wave","Foundation","Parisian public life and a woman's changing self-perception are explored through a near-real-time journey.","Listening / subtext","Compare a woman's artistic identity with Charulata while retaining each film's context.","Where does the character stop performing for others and begin observing them?","https://www.criterion.com/films/244","Criterion","Anxiety about illness."],
    ["do-right","Do the Right Thing",1989,["Spike Lee"],"United States","United States","English",120,"Black American cinema","Foundation","A Brooklyn block, music and racial tensions form a landmark of politically engaged American cinema.","Ensemble / space","Compare ensemble social conflict with Mrinal Sen, then identify differences rather than equating them.","How do address, distance and vocal rhythm redistribute status within the group?","https://www.criterion.com/films/286-do-the-right-thing","Criterion","Racism, strong language and violence."],
    ["parasite","Parasite",2019,["Bong Joon Ho"],"South Korea","South Korea","Korean",131,"New Korean Cinema / genre mixing","Foundation","Class inequality is expressed through contrasting households, architecture and shifting genres.","Ensemble / space","Compare class performance with Mrinal Sen; ask what the physical space contributes.","How does a character change their social mask when entering another household?","https://www.criterion.com/films/30619-parasite","Criterion","Strong violence and adult themes."],
    ["black-girl","Black Girl",1966,["Ousmane Sembène"],"Senegal","Senegal, France","French, Wolof",59,"Postcolonial African cinema","Foundation","Migration and domestic employment expose colonial power persisting after formal independence.","Voice / silence","Compare voice and social power with a Bengal text or film, using specific evidence.","What difference do you notice between spoken interaction and the character's inner voice?","https://www.criterion.com/films/28849-black-girl","Criterion","Racism and severe psychological distress; check content advice."],
    ["tokyo-story","Tokyo Story",1953,["Yasujiro Ozu"],"Japan","Japan","Japanese",137,"Postwar family drama","Foundation","Family obligations and generational distance make postwar social change intimate rather than spectacular.","Listening / subtext","Compare stillness and family relationships with Ray; do not equate their framing systems.","Which restrained response suggests a feeling that the dialogue leaves unstated?","https://www.criterion.com/films/284-tokyo-story","Criterion","Bereavement and family neglect."],
    ["close-up","Close-up",1990,["Abbas Kiarostami"],"Iran","Iran","Persian",98,"Documentary-fiction hybrid","Foundation","People involved in a real impersonation case play themselves, opening questions about identity and cinema's authority.","Identity / performance","Compare self-presentation with a Mrinal Sen work; distinguish reenactment from documentary evidence.","What evidence can distinguish an observed action from a reconstruction or a performed identity?","https://www.criterion.com/films/1092-close-up","Criterion","Arrest and social humiliation."],
    ["all-mother","All About My Mother",1999,["Pedro Almodóvar"],"Spain","Spain","Spanish",101,"Modern Spanish melodrama","Foundation","An unconventional chosen family, motherhood and theatre combine in a compassionate, performance-centred melodrama.","Identity / performance","Compare stage and private selves with Bengal actor-practitioners; retain the film's specific gender context.","How does a character's public persona differ from their behaviour in an intimate exchange?","https://www.criterion.com/films/29569","Criterion","Bereavement, sexual themes and illness."],
    ["breathless","Breathless",1960,["Jean-Luc Godard"],"France","France","French",90,"French New Wave","Movement landmark","Street shooting, jump cuts and self-conscious movie references disrupted conventional narrative polish.","Editing / actor contribution","Compare political or self-aware form with Mrinal Sen without claiming a direct influence.","Which impression is created by the actor, and which depends on a cut?","https://www.criterion.com/films/268","Criterion","Crime, violence and sexual themes."],
    ["eight-half","8½",1963,["Federico Fellini"],"Italy","Italy, France","Italian",138,"European modernism","Cult & experiments","A filmmaker's creative crisis becomes a dreamlike exploration of cinema, memory and spectacle.","Identity / performance","Compare stylised emotional expression with Ghatak; identify what each form asks of the actor.","What changes when the same character occupies an everyday scene and a fantasy?","https://www.criterion.com/films/150-8","Criterion","Adult and sexual themes."],
    ["persona","Persona",1966,["Ingmar Bergman"],"Sweden","Sweden","Swedish",83,"Psychological modernism","Cult & experiments","An actor and a nurse become the basis for a formally radical investigation of identity and communication.","Voice / silence","Compare silence in Charulata with silence here without assuming they have the same function.","How does an actor listening silently alter the speaking partner's apparent power?","https://www.criterion.com/films/28491-persona","Criterion","Disturbing imagery and adult themes; check detailed advice."],
    ["wings","Wings of Desire",1987,["Wim Wenders"],"Germany","Germany (catalogue grouping)","German, English, French",127,"Berlin city film / European art cinema","Movement landmark","A portrait of Berlin before the Wall fell combines inner voices, urban space and the desire for embodied life.","Voice / silence","Compare poetic voice and embodied gesture with a Tagore performance exercise.","How does a voice-over change your reading of a face that otherwise appears still?","https://www.criterion.com/films/200-wings-of-desire","Criterion","Loneliness and mortality themes."],
    ["jeanne","Jeanne Dielman, 23, quai du Commerce, 1080 Bruxelles",1975,["Chantal Akerman"],"Belgium","France, Belgium","French",201,"Feminist cinema / duration","Cult & experiments","Domestic routines and sustained duration make invisible labour and small disruptions central cinematic events.","Body / routine","Compare an everyday task in Ray with this film's treatment of repetition and duration.","How does a tiny change in an ordinary physical task acquire dramatic weight?","https://www.criterion.com/films/302-jeanne-dielman-23-quai-du-commerce-1080-bruxelles","Criterion","Sex work and violence; long, demanding viewing."],
    ["stalker","Stalker",1979,["Andrei Tarkovsky"],"Soviet Union","Soviet Union","Russian",161,"Soviet art cinema / philosophical science fiction","Cult & experiments","A journey through a restricted landscape makes space, duration and uncertain belief the material of science fiction.","Tempo / stillness","Compare sustained physical tension with a Ghatak scene; separate editing, sound and gesture.","What maintains tension when the actor is almost motionless?","https://www.criterion.com/films/28150-stalker","Criterion","Existential distress; slow, demanding viewing."],
    ["blue","Three Colors: Blue",1993,["Krzysztof Kieślowski"],"France / Polish filmmaker","France (catalogue grouping)","French",98,"Transnational European art cinema","Movement landmark","Grief and attempted liberation connect intimate experience with the trilogy's French revolutionary ideals.","Listening / subtext","Compare emotional withdrawal with a Ray performance; note the effects of music and colour.","Which physical action signals a decision before the character explains it?","https://www.criterion.com/films/27731-three-colors-blue","Criterion","Bereavement and emotional distress."],
    ["trainspotting","Trainspotting",1996,["Danny Boyle"],"United Kingdom / Scotland","United Kingdom","English",94,"1990s British youth culture","Cult & experiments","Scottish youth, addiction and a prominent soundtrack helped turn an independent film into a British pop-cultural event. BFI identifies the film as a cult classic.","Tempo / stillness","Compare heightened rhythm with a Ghatak performance; never imitate substance use for an exercise.","How do vocal rhythm and movement support the scene's changing energy?","https://www.criterion.com/films/29627-trainspotting","Criterion; BFI reception reference","Explicit drug use, sex and disturbing imagery."],
    ["mulholland","Mulholland Dr.",2001,["David Lynch"],"United States","United States (catalogue grouping)","English",146,"Dream logic / Hollywood neo-noir","Cult & experiments","Hollywood aspiration and unstable identity are refracted through a fractured, unsettling dream narrative.","Identity / performance","Compare a social mask with a Bengal performance; avoid reducing ambiguity to one correct answer.","How does the apparent reality of an exchange shift through performance rather than exposition?","https://www.criterion.com/films/28050-mulholland-dr","Criterion","Sexual content, violence and disturbing imagery."],
    ["yi-yi","Yi Yi",2000,["Edward Yang"],"Taiwan","Taiwan","Mandarin (catalogue primary language)",173,"New Taiwan Cinema","Movement landmark","An intergenerational Taipei family offers a way into urban modernity, private memory and everyday ethical choices.","Ensemble / space","Compare family relationships with Ray while observing Yang's use of wider frames.","What can you infer from a character's position in the frame without using a close-up?","https://www.criterion.com/films/781-yi-yi","Criterion","Family distress and bereavement; long viewing."],
    ["red-lantern","Raise the Red Lantern",1991,["Zhang Yimou"],"China","China, Hong Kong","Mandarin",125,"Fifth Generation Chinese cinema","Movement landmark","Household rituals and status make power and control visible in a defining Fifth Generation film.","Ensemble / space","Compare hierarchy expressed through gesture with a Bengal period scene.","How does a ritual change the status of each person sharing the space?","https://filmmovement.com/raise-the-red-lantern","Film Movement","Coercion and patriarchal oppression."],
    ["anatolia","Once Upon a Time in Anatolia",2011,["Nuri Bilge Ceylan"],"Turkey","Turkey (festival catalogue)","Turkish",157,"Contemporary Turkish art cinema","Movement landmark","A rural investigation reveals resentment and human complexity through apparently incidental conversation and gesture.","Listening / subtext","Compare everyday talk under pressure with a Ray scene; do not equate national character.","Which offhand response suggests an unresolved relationship?","https://www.filmlinc.org/films/once-upon-a-time-in-anatolia/","Film at Lincoln Center","Murder investigation and death; long viewing."],
    ["timbuktu","Timbuktu",2014,["Abderrahmane Sissako"],"Mali / Mauritania","France, Mauritania","Arabic, Bambara, French, English, Songhay, Tamasheq",97,"Transnational West African cinema","Movement landmark","A Mali-set drama attends to everyday dignity and resistance under occupation; production nationality differs from its setting.","Body / routine","Compare embodied resistance with a Bengal ensemble exercise, without reenacting violence.","How does an ordinary bodily action become an act of resistance?","https://www.filmlinc.org/films/timbuktu/","Film at Lincoln Center","Extremist oppression and violence."],
    ["city-god","City of God",2002,["Fernando Meirelles","Kátia Lund"],"Brazil","Brazil, France, Germany (institutional catalogue)","Portuguese",130,"Brazilian urban crime cinema","Movement landmark","A photographer's perspective and a kinetic ensemble portray violence in Rio's favelas; discuss whose perspective the film privileges.","Editing / actor contribution","Compare political representation with Mrinal Sen rather than treating either as documentary proof.","Which behaviour remains legible if you separate it from the film's energetic editing?","https://www.siskelfilmcenter.org/city-god","Gene Siskel Film Center / School of the Art Institute of Chicago","Strong violence, children in danger and adult themes."],
    ["y-tu-mama","Y tu mamá también",2001,["Alfonso Cuarón"],"Mexico","Mexico","Spanish",106,"Modern Mexican cinema / road film","Movement landmark","A road journey brings friendship, desire and unequal class positions into the same dramatic space.","Ensemble / space","Compare class tension with Mrinal Sen; distinguish intimate behaviour from narrator commentary.","When does intimacy conceal a change in status between the characters?","https://www.criterion.com/films/28005-y-tu-mam-tambi-n","Criterion","Explicit sex and adult themes."],
    ["cienaga","La Ciénaga",2001,["Lucrecia Martel"],"Argentina","Argentina (catalogue grouping)","Spanish",101,"New Argentine Cinema","Movement landmark","An extended family's stagnation and class relations emerge through bodily detail and on- and offscreen sound.","Ensemble / space","Compare domestic social tension with Ray or Sen while attending to offscreen sound.","How does an unseen sound change an actor's response to the room?","https://www.criterion.com/films/28113","Criterion","Injury, alcohol misuse and unsettling family dynamics."],
    ["four-months","4 Months, 3 Weeks and 2 Days",2007,["Cristian Mungiu"],"Romania","Romania","Romanian",113,"Romanian New Wave","Movement landmark","A day under the Ceaușescu dictatorship exposes coercion and impossible choices through rigorously realistic detail.","Objective / obstacle","Compare sustained pressure with an NSD scene exercise; do not reenact coercion or trauma.","How does an actor sustain a practical objective under changing threats?","https://www.criterion.com/films/28617-4-months-3-weeks-and-2-days","Criterion","Abortion, sexual coercion and graphic distress; optional, not compulsory."],
    ["piano","The Piano",1993,["Jane Campion"],"New Zealand / Australia","New Zealand, Australia, France","English, Māori",120,"Feminist cinema / colonial-period drama","Movement landmark","A woman's musical expression and struggle for agency place silence and embodiment at the centre of a New Zealand-set drama.","Voice / silence","Compare artistic expression with Charulata while respecting differences in colonial and gender context.","What physical choice conveys a demand without spoken language?","https://www.criterion.com/films/30424-the-piano","Criterion","Sexual content, coercion and violence." ]
  ].map(r => ({id:r[0],title:r[1],year:r[2],directors:r[3],region:r[4],countries:r[5],language:r[6],minutes:r[7],movement:r[8],path:r[9],context:r[10],focus:r[11],bengalBridge:r[12],question:r[13],url:r[14],publisher:r[15],advisory:r[16],sourceType:"supplementary",verifiedOn:"2026-09-26",access:"reference",availability:"lawful full-film availability not verified"})),
  receptionSources: [
    {title:"Trainspotting: cult reception",url:"https://www.bfi.org.uk/sight-and-sound/reviews/t2-trainspotting-review-diluted-fix-96",publisher:"BFI / Sight and Sound",verifiedOn:"2026-09-26"},
    {title:"Stalker: cult success and artistic legacy",url:"https://www.bfi.org.uk/sight-and-sound/features/tarkovsky-legacy",publisher:"BFI / Sight and Sound",verifiedOn:"2026-09-26"},
    {title:"Mulholland Dr.: cult-classic restoration programme",url:"https://nouveaucinema.ca/storage/document/2022-08-22/1753-021043.pdf",publisher:"Festival du nouveau cinéma",verifiedOn:"2026-09-26"}
  ],
  clipExercise: {title:"Charulata restored excerpt: Bengal comparison",url:"https://vimeo.com/57357485",rightsReference:"https://www.rdborganization.com/rdb/charulata.html",access:"Producer-linked excerpt, not a full film",verifiedOn:"2026-09-26"}
};

// Extend existing seeds without renaming any progress keys from earlier versions.
window.ACTING_SEED.tracks.push({id:"world",name:"International cinema · supplementary",modules:window.ACTING_CINEMA.modules});
window.ACTING_SEED.resources.push(...window.ACTING_CINEMA.films.map(f=>({id:`cinema-source-${f.id}`,track:"International",category:"supplementary film reference",title:`${f.title} (${f.year}) — ${f.directors.join(" / ")}`,url:f.url,access:f.access,publisher:f.publisher,sourceType:f.sourceType,verifiedOn:f.verifiedOn})));
window.ACTING_SEED.resources.push(...window.ACTING_CINEMA.receptionSources.map((r,i)=>({id:`cinema-reception-${i}`,track:"International",category:"supplementary reception reference",access:"reference",sourceType:"supplementary",...r})));
